apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp
    labels:
        type: server
spec:
    template:
        metadata:
            name: my-app-pod
            labels:
                type: server1
        spec:
             containers:
              - name: nginx-server
                image: nginx
    replicas: 3
