apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-02T04:51:54Z"
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
  resourceVersion: "931"
  uid: ebf0d812-dca2-42ab-b6be-9c89358dbc03
spec:
  containers:
  - envFrom:
      - configMapRef :
          name: webapp-config-map
    image: kodekloud/webapp-color
    imagePullPolicy: Always
    name: webapp-color
